# Generated by Django 3.2 on 2024-11-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flyers/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('الباب', 'الباب'), ('جنديرس', 'جنديرس')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='pages/')),
                ('working_hours', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=15)),
            ],
        ),
    ]
