# Generated by Django 3.2 on 2024-11-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='area',
            field=models.CharField(choices=[('الباب', 'الباب'), ('جنديرس', 'جنديرس')], default='الباب', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
