# Generated by Django 3.2 on 2024-11-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_page_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='area',
            field=models.CharField(choices=[('الباب', 'الباب'), ('جنديرس', 'جنديرس')], max_length=50),
        ),
    ]
